### ISSUE TITLE
xmessage window

### ISSUE THREAD

**Issue by MomoMoses** [openpreserve/ddhn-forge#32] opened 2020-11-20 02:32 UTC
xmessage window displays on first startup with this error message: "VBoxClient: Failed to get display change request, rc=VERR_TO_BAD_LENGTH

I "X"'d out the window, but it kept popping up later, particularly when I hit "Activities" and the screen formation changed.

**Comment by MomoMoses** [comment] 2020-11-20 02:38
![2020-11-19 16_49_56-DDHN Beta  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/3534298/99751093-24c92880-2aa7-11eb-8a2c-945e2d498803.jpg)

**Comment by carlwilson** [comment] 2020-11-24 13:50
Thanks, @MomoMoses this is a duplicate of #24 and I think is due to an unfortunate combination of VBox driver and provisioning mis-step by me. I believe (hope) I have a fix.

**Closed** 2022-12-15 15:36 UTC
Labels: bug, duplicate
